debug: true
server:
  port: 8001

spring:
  webflux:
    client:
      max-connections: 200
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"
      max-age: 3600

  main:
    allow-bean-definition-overriding: true

  # For database connection
  r2dbc:
    #    url: r2dbc:pool:mysql://inspectionsmanagementsystem.com/inspe7zg_foodswing?tlsVersion=TLSv1.2
    #    username: inspe7zg_appuser
    #    password: wl4G(IG3yVWc
    url: r2dbc:pool:mysql://localhost:3306/foodswing_local
    username: root
    password: root

springdoc:
  api-docs:
    path: /api-docs